"""Generates docs/WORKFLOW_ANALYSIS.md from the Excel file + bindings (so docs never drift from config).

    python scripts/generate_workflow_docs.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from agent.registry import WorkflowRegistry  # noqa: E402

# How each Excel decision rule is implemented (human explanation, kept next to the generator).
IMPLEMENTATION_NOTES = {
    "WF001": "`current_stock < threshold` where threshold = user override or product `minimum_stock` (equal stock is NOT flagged). "
             "Reorder qty = 2 × threshold − current stock, rounded up to the supplier case pack.",
    "WF002": "SKUs normalised (trim/upper-case) before matching. `|pct_difference| > 10` (exactly 10% is not an exception). "
             "Unmatched SKUs on either side are reported separately. A tolerance stated in the request overrides 10%.",
    "WF003": "Header aliases (config) map messy vendor headers to canonical fields; if SKU/name columns can't be detected the run fails "
             "with an actionable message. Only missing SKU or product name makes a row invalid (other issues are kept).",
    "WF004": "Product name + category are blocking (agent asks for them). Material/colour/attributes/audience are optional: if missing they are "
             "written as `[MISSING: field]`, never invented. Each text is length-validated (SEO title ≤ 60, meta ≤ 160); the LLM is asked to fix "
             "violations once, then text is trimmed.",
    "WF005": "Identifier must be `ORD-####` or an email, otherwise the agent asks. Order API is retried twice on transient errors. "
             "Not found → agent asks for another identifier (multi-turn; the new identifier replaces the old one). Shipment API failure "
             "degrades to 'tracking unavailable' instead of failing.",
    "WF006": "Exact SKU match (after normalisation) = Definite. Otherwise weighted similarity (name 45%, brand/colour/size 15% each, price ±5% 10%) "
             "≥ 0.85 = possible duplicate (High ≥ 0.95, else Medium). Different size or colour = variant, never a duplicate.",
    "WF007": "Goal, start date and end date are required (and dates must be valid and ordered) — otherwise the agent asks before generating. "
             "'New collection' is resolved from product data. Missing audience/promotion are marked, not invented.",
    "WF008": "Keywords de-duplicated case/space-insensitively. Intent ∈ {informational, commercial, transactional, navigational} via LLM "
             "(rule-based fallback). Target page: category page for buying intent, guide page for informational, utility page for navigational.",
    "WF009": "Required skills come from the task DB or are extracted from the description. Suitable = skill match ≥ 67% AND free hours ≥ "
             "task hours AND not on leave. Ranked by weighted score; if nobody is suitable the run is ESCALATED.",
    "WF010": "Run-level roll-up of step logs. Flag = failure rate > 10% OR average run time > 8000 ms. Slow steps = average > 3000 ms. "
             "Recommendations are mapped from error patterns (timeouts, 429s, encoding, …).",
}


def main() -> None:
    reg = WorkflowRegistry.load()
    out = ["# Workflow analysis\n",
           "_Generated by `scripts/generate_workflow_docs.py` from `workflows/AI_Agent_Workflow_Assessment.xlsx` and "
           "`config/workflow_bindings.yaml`._\n",
           "For each workflow: input, required steps (and the tool executing each), tools/APIs, conditions/decisions, "
           "expected output, and how the decision logic was interpreted.\n",
           "| ID | Workflow | Excel test request |", "|---|---|---|"]
    tests = {t["Workflow_ID"]: t["Test_Request"] for t in reg.test_questions}
    out += [f"| {w.id} | [{w.name}](#{w.id.lower()}--{w.name.lower().replace(' ', '-')}) | {tests.get(w.id, '')} |"
            for w in reg.workflows.values()]
    for w in reg.workflows.values():
        out += [f"\n## {w.id} — {w.name}\n",
                f"**Trigger:** {w.trigger}  ",
                f"**Inputs (Excel):** {w.inputs}  ",
                f"**Tools required (Excel):** {w.tools_required}  ",
                f"**Decision logic (Excel):** {w.decision_logic}  ",
                f"**Expected output (Excel):** {w.expected_output}\n",
                "**Parameters the agent extracts from the request:**\n"]
        for p in w.params:
            flags = []
            if p.default is not None:
                flags.append(f"default `{p.default}`")
            if not p.llm:
                flags.append("from attachment/default only")
            out.append(f"- `{p.name}` ({p.type}) — {p.description}{' · ' + ', '.join(flags) if flags else ''}")
        if w.settings:
            out.append("\n**Settings (decision thresholds, config not code):** " +
                       ", ".join(f"`{k}`={v}" for k, v in w.settings.items() if not isinstance(v, (dict, list))
                                 ) + (" (+ structured settings in YAML)" if any(isinstance(v, (dict, list)) for v in w.settings.values()) else ""))
        out += ["\n**Steps → tools:**\n", "| # | Step (Excel) | Tool | Policy |", "|---|---|---|---|"]
        for i, s in enumerate(w.steps, 1):
            pol = [f"retries={s.retries}"] if s.retries else []
            if s.on_error != "fail":
                pol.append(f"on_error={s.on_error}")
            out.append(f"| {i} | {s.label} | `{s.tool}` | {', '.join(pol) or '-'} |")
        out.append(f"\n**Conditions / decisions as implemented:** {IMPLEMENTATION_NOTES.get(w.id, '-')}\n")
    path = ROOT / "docs" / "WORKFLOW_ANALYSIS.md"
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
